global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  resolution: 0.2
  static_map: true
  rolling_window: false 
  width: 15.0
  height: 15.0


  plugins:
     - {name: static,                    type: "costmap_2d::StaticLayer"}
     - {name: inflation,                 type: "costmap_2d::InflationLayer"}
     - {name: obstacle,                 type: "costmap_2d::ObstacleLayer"}
