local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  static_map: false
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05


  plugins:
     - {name: static,                    type: "costmap_2d::StaticLayer"}
     - {name: inflation,                 type: "costmap_2d::InflationLayer"}
     - {name: obstacle,                 type: "costmap_2d::ObstacleLayer"}
